version = 1

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  java_version = "8"
  gradle_modules = [
    # ":boms",
    # ":boms:geode-all-bom",
    # ":boms:geode-client-bom",
    # ":extensions",
    ":extensions:geode-modules",
    ":extensions:geode-modules-assembly",
    ":extensions:geode-modules-session",
    ":extensions:geode-modules-session-internal",
    # ":extensions:geode-modules-test",
    ":extensions:geode-modules-tomcat7",
    ":extensions:geode-modules-tomcat8",
    ":extensions:geode-modules-tomcat9",
    # ":extensions:session-testing-war",
    # ":geode-assembly",
    # ":geode-assembly:geode-assembly-test",
    ":geode-common",
    # ":geode-concurrency-test",
    ":geode-connectors",
    ":geode-core",
    ":geode-cq",
    ":geode-dunit",
    # ":geode-experimental-driver",
    ":geode-gfsh",
    ":geode-http-service",
    ":geode-jmh",
    ":geode-junit",
    ":geode-log4j",
    ":geode-logging",
    ":geode-lucene",
    # ":geode-lucene:geode-lucene-test",
    ":geode-management",
    ":geode-membership",
    ":geode-memcached",
    # ":geode-old-client-support",
    # ":geode-old-versions",
    # ":geode-old-versions:1.0.0-incubating",
    # ":geode-old-versions:1.1.0",
    # ":geode-old-versions:1.1.1",
    # ":geode-old-versions:1.10.0",
    # ":geode-old-versions:1.11.0",
    # ":geode-old-versions:1.12.0",
    # ":geode-old-versions:1.13.0",
    # ":geode-old-versions:1.2.0",
    # ":geode-old-versions:1.3.0",
    # ":geode-old-versions:1.4.0",
    # ":geode-old-versions:1.5.0",
    # ":geode-old-versions:1.6.0",
    # ":geode-old-versions:1.7.0",
    # ":geode-old-versions:1.8.0",
    # ":geode-old-versions:1.9.0",
    # ":geode-old-versions:1.9.1",
    # ":geode-old-versions:1.9.2",
    # ":geode-protobuf",
    # ":geode-protobuf:geode-protobuf-test",
    # ":geode-protobuf-messages",
    ":geode-pulse",
    # ":geode-pulse:geode-pulse-test",
    ":geode-rebalancer",
    ":geode-redis",
    ":geode-serialization",
    ":geode-tcp-server",
    ":geode-unsafe",
    ":geode-wan",
    ":geode-web",
    ":geode-web-api"
    # ":geode-web-management",
    # ":static-analysis",
    # ":static-analysis:pmd-rules"
  ]
